// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

module ``documentation generator``.``links json artifact``

open Xunit
open authoring

type ``two pages with anchors end up in artifact`` () =

    static let generator = Setup.Generate [
        Index """
# A Document that lives at the root

*Welcome* to this documentation

## This anchor is autogenerated

### Several pages can be created [#and-anchored]

Through various means $$$including-this-inline-syntax$$$
"""
        Markdown "file.md" "*hello* world"
    ]

    [<Fact>]
    let ``validate index.md HTML`` () =
        generator |> converts "index.md" |> toHtml """
             <p>
 	            <em>Welcome</em>
 	            to this documentation</p>
             <div class="heading-wrapper" id="this-anchor-is-autogenerated">
 	            <h2>
 		            <a class="headerlink" href="#this-anchor-is-autogenerated">This anchor is autogenerated</a>
 	            </h2>
             </div>
             <div class="heading-wrapper" id="and-anchored">
 	            <h3>
 		            <a class="headerlink" href="#and-anchored">Several pages can be created</a>
 	            </h3>
             </div>
             <p>Through various means
 	            <a id="including-this-inline-syntax"></a>
             </p>
        """

    [<Fact>]
    let ``validate file.md HTML`` () =
        generator |> converts "file.md" |> toHtml "<p><em>hello</em>world</p>"

    [<Fact>]
    let ``has no errors`` () = generator |> hasNoErrors

    [<Fact>]
    let ``validate links.json`` () =
        generator |> convertsToJson ".artifacts/docs/html/links.json" """
        {
          "origin": {
            "branch": "test-e35fcb27-5f60-4e",
            "remote": "elastic/docs-builder",
            "ref": "e35fcb27-5f60-4e"
          },
          "url_path_prefix": "",
          "links": {
            "file.md": {},
            "index.md": {
              "anchors":[
                "including-this-inline-syntax",
                "this-anchor-is-autogenerated",
                "and-anchored"
              ]
            }
          },
          "cross_links": []
        }
        """
